"""add summary to issue_reports

Revision ID: 0c1504c8eed1
Revises: 5c5389079447
Create Date: 2026-06-12 15:07:39.510267
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0c1504c8eed1'
down_revision: Union[str, None] = '5c5389079447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_reports', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_reports', 'summary')
    # ### end Alembic commands ###
