"""add controller_support and steam_deck_status

Revision ID: e0fc6113482c
Revises: 0c1504c8eed1
Create Date: 2026-06-12 15:56:13.868595
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e0fc6113482c'
down_revision: Union[str, None] = '0c1504c8eed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('controller_support', sa.String(length=50), nullable=True))
    op.add_column('games', sa.Column('steam_deck_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'steam_deck_status')
    op.drop_column('games', 'controller_support')
    # ### end Alembic commands ###
