"""Seed 20 curated games with known health profiles for development."""
from datetime import date, datetime

from src.database import SessionLocal, engine, Base
from src.models import Game, Review, PlayerMetric, HealthScore, IssueReport, Patch

SEED_GAMES = [
    # --- Healthy games (score 80+) ---
    {
        "steam_app_id": 814380,
        "name": "Sekiro: Shadows Die Twice",
        "release_date": date(2019, 3, 22),
        "developer": "FromSoftware",
        "publisher": "Activision",
        "platforms": "PC, PS4, Xbox One",
        "genre": "Action, RPG",
        "score": 95,
        "sentiment": 92,
        "stability": 97,
        "retention": 94,
        "developer_support": 90,
        "recommendation": "BUY NOW",
    },
    {
        "steam_app_id": 1245620,
        "name": "Elden Ring",
        "release_date": date(2022, 2, 25),
        "developer": "FromSoftware",
        "publisher": "Bandai Namco",
        "platforms": "PC, PS4, PS5, Xbox One, Xbox Series X",
        "genre": "Action, RPG",
        "score": 93,
        "sentiment": 90,
        "stability": 95,
        "retention": 91,
        "developer_support": 88,
        "recommendation": "BUY NOW",
    },
    {
        "steam_app_id": 413150,
        "name": "Stardew Valley",
        "release_date": date(2016, 2, 26),
        "developer": "ConcernedApe",
        "publisher": "ConcernedApe",
        "platforms": "PC, Mac, Linux, Switch, PS4, Xbox One, Mobile",
        "genre": "Simulation, RPG",
        "score": 98,
        "sentiment": 97,
        "stability": 99,
        "retention": 96,
        "developer_support": 100,
        "recommendation": "BUY NOW",
    },
    {
        "steam_app_id": 105600,
        "name": "Terraria",
        "release_date": date(2011, 5, 16),
        "developer": "Re-Logic",
        "publisher": "Re-Logic",
        "platforms": "PC, Mac, Linux, Console, Mobile",
        "genre": "Sandbox, Action",
        "score": 96,
        "sentiment": 95,
        "stability": 97,
        "retention": 94,
        "developer_support": 92,
        "recommendation": "BUY NOW",
    },
    {
        "steam_app_id": 730,
        "name": "Counter-Strike 2",
        "release_date": date(2023, 9, 27),
        "developer": "Valve",
        "publisher": "Valve",
        "platforms": "PC",
        "genre": "FPS, Competitive",
        "score": 82,
        "sentiment": 75,
        "stability": 85,
        "retention": 90,
        "developer_support": 78,
        "recommendation": "BUY NOW",
    },
    # --- Recovered games (were bad, now good, score 70-85) ---
    {
        "steam_app_id": 271590,
        "name": "Grand Theft Auto V",
        "release_date": date(2015, 4, 14),
        "developer": "Rockstar North",
        "publisher": "Rockstar Games",
        "platforms": "PC, PS3, PS4, PS5, Xbox 360, Xbox One, Xbox Series X",
        "genre": "Action, Adventure",
        "score": 85,
        "sentiment": 80,
        "stability": 88,
        "retention": 87,
        "developer_support": 82,
        "recommendation": "BUY NOW",
    },
    {
        "steam_app_id": 255710,
        "name": "Cities: Skylines",
        "release_date": date(2015, 3, 10),
        "developer": "Colossal Order",
        "publisher": "Paradox Interactive",
        "platforms": "PC, Mac, Linux, Console",
        "genre": "Simulation, Strategy",
        "score": 83,
        "sentiment": 81,
        "stability": 85,
        "retention": 82,
        "developer_support": 79,
        "recommendation": "BUY NOW",
    },
    {
        "steam_app_id": 892970,
        "name": "Valheim",
        "release_date": date(2021, 2, 2),
        "developer": "Iron Gate",
        "publisher": "Coffee Stain Publishing",
        "platforms": "PC, Xbox One, Xbox Series X",
        "genre": "Survival, Open World",
        "score": 78,
        "sentiment": 73,
        "stability": 80,
        "retention": 79,
        "developer_support": 80,
        "recommendation": "PLAYABLE",
    },
    # --- Mixed games (some issues, score 55-70) ---
    {
        "steam_app_id": 1091500,
        "name": "Cyberpunk 2077",
        "release_date": date(2020, 12, 10),
        "developer": "CD Projekt Red",
        "publisher": "CD Projekt",
        "platforms": "PC, PS4, PS5, Xbox One, Xbox Series X",
        "genre": "RPG, Open World",
        "score": 68,
        "sentiment": 62,
        "stability": 72,
        "retention": 69,
        "developer_support": 70,
        "recommendation": "PLAYABLE",
    },
    {
        "steam_app_id": 1174180,
        "name": "Red Dead Redemption 2",
        "release_date": date(2019, 12, 5),
        "developer": "Rockstar Games",
        "publisher": "Rockstar Games",
        "platforms": "PC, PS4, Xbox One",
        "genre": "Action, Adventure",
        "score": 72,
        "sentiment": 68,
        "stability": 74,
        "retention": 73,
        "developer_support": 71,
        "recommendation": "PLAYABLE",
    },
    {
        "steam_app_id": 1551360,
        "name": "Forza Horizon 5",
        "release_date": date(2021, 11, 9),
        "developer": "Playground Games",
        "publisher": "Xbox Game Studios",
        "platforms": "PC, Xbox One, Xbox Series X",
        "genre": "Racing, Open World",
        "score": 75,
        "sentiment": 70,
        "stability": 78,
        "retention": 76,
        "developer_support": 75,
        "recommendation": "PLAYABLE",
    },
    {
        "steam_app_id": 1240440,
        "name": "Hollow Knight: Silksong",
        "release_date": date(2025, 6, 1),
        "developer": "Team Cherry",
        "publisher": "Team Cherry",
        "platforms": "PC, Switch",
        "genre": "Metroidvania, Action",
        "score": 70,
        "sentiment": 65,
        "stability": 75,
        "retention": 70,
        "developer_support": 68,
        "recommendation": "PLAYABLE",
    },
    # --- Struggling games (score 40-60) ---
    {
        "steam_app_id": 1282730,
        "name": "Starfield",
        "release_date": date(2023, 9, 6),
        "developer": "Bethesda Game Studios",
        "publisher": "Bethesda Softworks",
        "platforms": "PC, Xbox Series X",
        "genre": "RPG, Open World",
        "score": 52,
        "sentiment": 45,
        "stability": 58,
        "retention": 54,
        "developer_support": 48,
        "recommendation": "WAIT FOR PATCHES",
    },
    {
        "steam_app_id": 945360,
        "name": "Among Us",
        "release_date": date(2018, 6, 15),
        "developer": "Innersloth",
        "publisher": "Innersloth",
        "platforms": "PC, Mobile, Console",
        "genre": "Social Deduction",
        "score": 60,
        "sentiment": 55,
        "stability": 65,
        "retention": 58,
        "developer_support": 60,
        "recommendation": "PLAYABLE",
    },
    {
        "steam_app_id": 1085660,
        "name": "Destiny 2",
        "release_date": date(2019, 10, 1),
        "developer": "Bungie",
        "publisher": "Bungie",
        "platforms": "PC, PS4, PS5, Xbox One, Xbox Series X",
        "genre": "FPS, Looter Shooter",
        "score": 58,
        "sentiment": 50,
        "stability": 62,
        "retention": 60,
        "developer_support": 58,
        "recommendation": "WAIT FOR PATCHES",
    },
    # --- Bad games (score < 40) ---
    {
        "steam_app_id": 2358720,
        "name": "Black Myth: Wukong",
        "release_date": date(2024, 8, 20),
        "developer": "Game Science",
        "publisher": "Game Science",
        "platforms": "PC, PS5",
        "genre": "Action, RPG",
        "score": 38,
        "sentiment": 35,
        "stability": 40,
        "retention": 38,
        "developer_support": 35,
        "recommendation": "AVOID FOR NOW",
    },
    {
        "steam_app_id": 367520,
        "name": "Hollow Knight",
        "release_date": date(2017, 2, 24),
        "developer": "Team Cherry",
        "publisher": "Team Cherry",
        "platforms": "PC, Mac, Linux, Switch, PS4, Xbox One",
        "genre": "Metroidvania, Action",
        "score": 35,
        "sentiment": 32,
        "stability": 38,
        "retention": 34,
        "developer_support": 32,
        "recommendation": "AVOID FOR NOW",
    },
    {
        "steam_app_id": 489830,
        "name": "The Elder Scrolls V: Skyrim Special Edition",
        "release_date": date(2016, 10, 28),
        "developer": "Bethesda Game Studios",
        "publisher": "Bethesda Softworks",
        "platforms": "PC, PS4, Xbox One, Switch",
        "genre": "RPG, Open World",
        "score": 42,
        "sentiment": 38,
        "stability": 44,
        "retention": 42,
        "developer_support": 40,
        "recommendation": "AVOID FOR NOW",
    },
    {
        "steam_app_id": 1593500,
        "name": "God of War",
        "release_date": date(2022, 1, 14),
        "developer": "Santa Monica Studio",
        "publisher": "Sony Interactive Entertainment",
        "platforms": "PC, PS4, PS5",
        "genre": "Action, Adventure",
        "score": 40,
        "sentiment": 36,
        "stability": 42,
        "retention": 40,
        "developer_support": 38,
        "recommendation": "AVOID FOR NOW",
    },
]

SEED_REVIEWS = [
    {"review_text": "Amazing game, no issues at all.", "recommended": True, "playtime": 120.5},
    {"review_text": "Crashes every 10 minutes, unplayable.", "recommended": False, "playtime": 2.3},
    {"review_text": "Performance is great, solid 60fps.", "recommended": True, "playtime": 85.0},
    {"review_text": "Game freezes during cutscenes.", "recommended": False, "playtime": 15.0},
    {"review_text": "Servers are always down, can't connect.", "recommended": False, "playtime": 0.5},
    {"review_text": "Beautiful world, minor stutters.", "recommended": True, "playtime": 200.0},
    {"review_text": "Save file corrupted after 50 hours.", "recommended": False, "playtime": 50.0},
    {"review_text": "Perfect optimization, runs like butter.", "recommended": True, "playtime": 60.0},
    {"review_text": "Constant disconnects in multiplayer.", "recommended": False, "playtime": 10.0},
    {"review_text": "Great game, needs a few patches.", "recommended": True, "playtime": 45.0},
]


def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        existing = db.query(Game).count()
        if existing > 0:
            print(f"Database already has {existing} games. Skipping seed.")
            return

        for game_data in SEED_GAMES:
            game = Game(
                steam_app_id=game_data["steam_app_id"],
                name=game_data["name"],
                release_date=game_data["release_date"],
                developer=game_data["developer"],
                publisher=game_data["publisher"],
                platforms=game_data["platforms"],
                genre=game_data["genre"],
            )
            db.add(game)
            db.flush()

            health = HealthScore(
                game_id=game.id,
                score=game_data["score"],
                sentiment=game_data["sentiment"],
                stability=game_data["stability"],
                retention=game_data["retention"],
                developer_support=game_data["developer_support"],
                recommendation=game_data["recommendation"],
                created_at=datetime.now(),
            )
            db.add(health)

            for i, review in enumerate(SEED_REVIEWS):
                r = Review(
                    review_id=f"seed_{game.id}_{i}",
                    game_id=game.id,
                    review_text=review["review_text"],
                    recommended=review["recommended"],
                    playtime=review["playtime"],
                    created_at=datetime.now(),
                )
                db.add(r)

            db.flush()

        db.commit()
        print(f"Seeded {len(SEED_GAMES)} games with {len(SEED_REVIEWS)} reviews each.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
